### ISSUE TITLE
Update simapp

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/cosmjs#377]
Let's follow Cosmos SDK development step by step, adapting our code as needed along the way.

- [x] to `nightly-2020-08-11` and `REF=20c80cfd44a068a592148d648c50de3459fd6295` #381 
- [ ] to `nightly-2020-08-12` and `REF=7ea64676788f2d550a65d86cd6b4cdfe89e9a49b` (blocked by https://github.com/cosmos/cosmos-sdk/issues/7026)
- [ ] to `nightly-2020-08-13` (blocked by https://github.com/cosmos/cosmos-sdk/issues/7026)
- [ ] to `nightly-2020-08-14` (blocked by https://github.com/cosmos/cosmos-sdk/issues/7026)
- [ ] to `nightly-2020-08-15` (blocked by https://github.com/cosmos/cosmos-sdk/issues/7026) (requires Tendermint 0.34)
- [ ] to `nightly-2020-08-16` (requires Tendermint 0.34)
- [ ] to `nightly-2020-08-17` (requires Tendermint 0.34)
- [ ] to `nightly-2020-08-18` (requires Tendermint 0.34)
- [ ] to `nightly-2020-08-19` (requires Tendermint 0.34)

**Comment by willclarktech** [comment]
@webmaster128 Is this checklist still accurate?

**Comment by webmaster128** [comment]
I think there is nothing wrong with the existing entries but we should try to fast-forward to today's simapp version.

**Comment by willclarktech** [comment]
Blocked by #451
