### ISSUE TITLE
Documentation Meta Issue

### ISSUE THREAD

**Issue by okwme** [CosmWasm/cosmjs#429]
Beginning with the Wiki section on "[What can CosmJS do fo me?](https://github.com/CosmWasm/cosmjs/wiki/What-can-CosmJS-do-for-me%3F)" thought it would be good to keep track of various documentation topics that are currently missing or might be good to have somewhere. This issue can also be a place to include links to snippets of code that might already be available in various capacities.

- [ ] Create various unsigned Cosmos Hub transactions?
- [ ] Sign an unsigned transaction when I have a mnemonic phrase? (12 word? 24 word?)
- [ ] Sign an unsigned transaction when I have a private key?
- [ ] Submit a signed transaction to a Cosmos Hub endpoint?
- [ ] Create a multi-sig signature on an unsigned transaction?
- [ ] Query state from a Cosmos Hub module using the legacy REST endpoint?
- [ ] Query state from a Cosmos Hub module using the gRPC endpoint?
- [ ] Query state from a custom module using the legacy REST endpoint?
- [ ] Query state from a custom module using the gRPC endpoint?

Would be great to see if some of this could be supported by aib as mentioned on a previous call.

**Comment by okwme** [comment]
cc @lukitsbrian @Tosch110
